// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE4dNB26NZxZeZuf7aYg5y_BQKeQeyVGE',
    appId: '1:446018040628:web:fbde1100616fff6d64ab61',
    messagingSenderId: '446018040628',
    projectId: 'ecotrack-d1bc7',
    authDomain: 'ecotrack-d1bc7.firebaseapp.com',
    storageBucket: 'ecotrack-d1bc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsj7q6JG0K58ToatWcroLz3K4s0kMQLy0',
    appId: '1:446018040628:android:59f9b0a3960ca9e564ab61',
    messagingSenderId: '446018040628',
    projectId: 'ecotrack-d1bc7',
    storageBucket: 'ecotrack-d1bc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZerzlBoopFjOrqiW0FnOVc-fNeJE3vgY',
    appId: '1:446018040628:ios:6b4e6e7af211f9dc64ab61',
    messagingSenderId: '446018040628',
    projectId: 'ecotrack-d1bc7',
    storageBucket: 'ecotrack-d1bc7.appspot.com',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZerzlBoopFjOrqiW0FnOVc-fNeJE3vgY',
    appId: '1:446018040628:ios:6b4e6e7af211f9dc64ab61',
    messagingSenderId: '446018040628',
    projectId: 'ecotrack-d1bc7',
    storageBucket: 'ecotrack-d1bc7.appspot.com',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE4dNB26NZxZeZuf7aYg5y_BQKeQeyVGE',
    appId: '1:446018040628:web:babab9c2c095a9d064ab61',
    messagingSenderId: '446018040628',
    projectId: 'ecotrack-d1bc7',
    authDomain: 'ecotrack-d1bc7.firebaseapp.com',
    storageBucket: 'ecotrack-d1bc7.appspot.com',
  );
}
